// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-MoGTxWIuL0rgFC_m6TCRUWk-wfGSxTM',
    appId: '1:427498364890:web:707812ea4becfc12fdaae3',
    messagingSenderId: '427498364890',
    projectId: 'my-notes-flutter-newproject',
    authDomain: 'my-notes-flutter-newproject.firebaseapp.com',
    storageBucket: 'my-notes-flutter-newproject.firebasestorage.app',
    measurementId: 'G-93ESJS15NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuOrN3CFRIUYbo4mNnDtKMegPvV0dDAeE',
    appId: '1:427498364890:android:2d93fa1ba84c828ffdaae3',
    messagingSenderId: '427498364890',
    projectId: 'my-notes-flutter-newproject',
    storageBucket: 'my-notes-flutter-newproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgdbvbtNBbZNirf_dObGm1C2k2iy9huck',
    appId: '1:427498364890:ios:578a90e4bec28957fdaae3',
    messagingSenderId: '427498364890',
    projectId: 'my-notes-flutter-newproject',
    storageBucket: 'my-notes-flutter-newproject.firebasestorage.app',
    iosBundleId: 'com.firstprojectflutter.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgdbvbtNBbZNirf_dObGm1C2k2iy9huck',
    appId: '1:427498364890:ios:578a90e4bec28957fdaae3',
    messagingSenderId: '427498364890',
    projectId: 'my-notes-flutter-newproject',
    storageBucket: 'my-notes-flutter-newproject.firebasestorage.app',
    iosBundleId: 'com.firstprojectflutter.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-MoGTxWIuL0rgFC_m6TCRUWk-wfGSxTM',
    appId: '1:427498364890:web:568bdf9fe1ac480dfdaae3',
    messagingSenderId: '427498364890',
    projectId: 'my-notes-flutter-newproject',
    authDomain: 'my-notes-flutter-newproject.firebaseapp.com',
    storageBucket: 'my-notes-flutter-newproject.firebasestorage.app',
    measurementId: 'G-CE8KW3DNLR',
  );
}
